'use client';

import Link from 'next/link';
import {
  NotebookIcon,
  SparklesIcon,
  PlayIcon,
  DocumentIcon
} from '@/components/Icons';
import Header from '@/components/layout/Header';
import NotebookItemCard from '@/components/ui/NotebookItemCard';
import { notebookItems } from '@/lib/notebook-data';

export default function NotebookPage() {
  return (
    <div className="min-h-screen">
      <Header
        title="The Notebook"
        subtitle="AI-generated insights, audio overviews & deep dives"
        icon={<NotebookIcon size={24} color="var(--glacial-600)" />}
        showBackLink={true}
      />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Intro Section */}
        <section className="frost-card-strong rounded-2xl shadow-xl p-8 mb-10 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 opacity-10" style={{
            background: 'radial-gradient(circle, var(--glacial-300) 0%, transparent 70%)',
            transform: 'translate(30%, -30%)'
          }} />
          <div className="relative">
            <div className="flex items-center gap-3 mb-4">
              <SparklesIcon size={28} color="var(--glacial-500)" />
              <h2 className="text-2xl font-bold" style={{ color: 'var(--glacial-800)' }}>
                AI-Generated Summit Insights
              </h2>
            </div>
            <p className="text-lg mb-4" style={{ color: 'var(--sage-700)' }}>
              This page hosts content generated by Google&apos;s NotebookLM from the complete Nordic Circular Summit 2025 documentation.
              Explore AI-powered summaries, audio overviews, and deep-dive analyses of the summit&apos;s key themes and discussions.
            </p>
            <div className="flex flex-wrap gap-3">
              <div className="flex items-center gap-2 px-3 py-2 rounded-lg" style={{ background: 'var(--glacial-100)' }}>
                <PlayIcon size={16} color="var(--glacial-600)" />
                <span className="text-sm font-medium" style={{ color: 'var(--glacial-700)' }}>Audio Overviews</span>
              </div>
              <div className="flex items-center gap-2 px-3 py-2 rounded-lg" style={{ background: 'var(--sage-100)' }}>
                <DocumentIcon size={16} color="var(--sage-600)" />
                <span className="text-sm font-medium" style={{ color: 'var(--sage-700)' }}>AI Summaries</span>
              </div>
              <div className="flex items-center gap-2 px-3 py-2 rounded-lg" style={{ background: '#ede9fe' }}>
                <NotebookIcon size={16} color="#7c3aed" />
                <span className="text-sm font-medium" style={{ color: '#7c3aed' }}>FAQ & Deep Dives</span>
              </div>
            </div>
          </div>
        </section>

        {/* Content Grid */}
        {notebookItems.length > 0 ? (
          <div className="grid md:grid-cols-2 gap-6">
            {notebookItems.map((item) => (
              <NotebookItemCard key={item.id} item={item} />
            ))}
          </div>
        ) : (
          /* Empty State */
          <div className="frost-card rounded-2xl shadow-lg p-12 text-center">
            <div className="flex justify-center mb-6">
              <div className="p-4 rounded-full" style={{ background: 'var(--glacial-100)' }}>
                <NotebookIcon size={48} color="var(--glacial-400)" />
              </div>
            </div>
            <h3 className="text-xl font-bold mb-3" style={{ color: 'var(--glacial-700)' }}>
              Content Coming Soon
            </h3>
            <p className="text-lg mb-6 max-w-md mx-auto" style={{ color: 'var(--sage-600)' }}>
              NotebookLM is processing the summit documentation. Audio overviews, summaries, and AI-generated insights will appear here.
            </p>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-lg" style={{ background: 'var(--sage-5)', border: '1px solid var(--sage-200)' }}>
              <SparklesIcon size={18} color="var(--sage-500)" />
              <span className="text-sm" style={{ color: 'var(--sage-600)' }}>
                40 documents uploaded to NotebookLM
              </span>
            </div>
          </div>
        )}

        {/* Source Info */}
        <section className="mt-12 p-6 rounded-xl" style={{ background: 'var(--sage-50)', border: '1px solid var(--sage-200)' }}>
          <h3 className="font-bold mb-3 flex items-center gap-2" style={{ color: 'var(--glacial-700)' }}>
            <DocumentIcon size={20} color="var(--glacial-600)" />
            Source Documentation
          </h3>
          <p className="text-sm mb-4" style={{ color: 'var(--sage-600)' }}>
            The Notebook content is generated from 40 comprehensive documents including:
          </p>
          <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div className="p-3 rounded-lg bg-white">
              <div className="font-semibold" style={{ color: 'var(--glacial-700)' }}>9 Transcripts</div>
              <div style={{ color: 'var(--sage-500)' }}>Full session recordings</div>
            </div>
            <div className="p-3 rounded-lg bg-white">
              <div className="font-semibold" style={{ color: 'var(--glacial-700)' }}>9 Articles</div>
              <div style={{ color: 'var(--sage-500)' }}>Long-form session writeups</div>
            </div>
            <div className="p-3 rounded-lg bg-white">
              <div className="font-semibold" style={{ color: 'var(--glacial-700)' }}>9 Quote Collections</div>
              <div style={{ color: 'var(--sage-500)' }}>Key quotes & themes</div>
            </div>
            <div className="p-3 rounded-lg bg-white">
              <div className="font-semibold" style={{ color: 'var(--glacial-700)' }}>53+ Speakers</div>
              <div style={{ color: 'var(--sage-500)' }}>Complete directory</div>
            </div>
          </div>
        </section>

        {/* Powered By */}
        <div className="mt-8 text-center">
          <p className="text-sm" style={{ color: 'var(--sage-500)' }}>
            Powered by{' '}
            <a
              href="https://notebooklm.google.com"
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium hover:underline"
              style={{ color: 'var(--glacial-600)' }}
            >
              Google NotebookLM
            </a>
          </p>
        </div>
      </main>
    </div>
  );
}